### ISSUE TITLE
[Bug] Starting the backend server re-create the tables everytime

### ISSUE THREAD

**Issue by longnd** [myat-hsu-mon/web-scrapping-app#24]
## Issue
Running the command to start the backend web server, `npm run dev` will drop & re-create the tables every time. 
It is because of the `force: true` attribute in the models

https://github.com/myat-hsu-mon/web-scrapping-app/blob/120bc39b82ccb5a1e9c3da8f92aee776fbe7f717/server/src/models/keywordModel.js#L13

It is not necessary to fix as it is an easy one to address. I'm just wondering why you decided to define the model like that and didn't you face that issue during your development process?

**Comment by myat-hsu-mon** [comment]
I tested some intentional cases on my local setup using `Model.sync({ force: true })`. I forgot to remove them before pushing the changes to Git. I've fixed this by adjusting the model definition and updating the migrations to define the models. This should solve the issue and make development faster. Thanks for your understanding and suggestions! If you have more ideas, feel free to share.
